### ISSUE TITLE
Review "Read Through Docs" and "ReadMe.io"

### ISSUE THREAD

**Issue by magneticmg** [nooku/guides.nooku.org#12]
Simple review of http://docs.readthedocs.org/en/latest/getting_started.html against our usage of Gitbook for Guides.

**Comment by magneticmg** [comment]
Have attempted to use both packages. 
ReadMe.io's github import is disabled because of demand. I've signed up for notification as to when it's turned back on.
This package builds its API references with apidocjs (http://apidocjs.com/) annotations that go into the source code. 

RTD is having some difficulty building our docs. Its running into some errors relating to the markdown. 
I have yet to dig into the API reference and how to do that with RTD.

**Comment by magneticmg** [comment]
@johanjanssens 
Just making a note here under this ticket in relation to the email I sent: 

Given our talks about other document publishing platforms and the work we've already done with the current Gitbook set up, e.g. apiary, I'm not seeing any clear advantage to switching over do a little styling work. In fact, Gitbook is great on mobile. 

So, I took a little time this morning to mock this up with inspector. Highlights:
https://www.dropbox.com/s/pyqvm4ijgebixp4/guides-proposed-style-changes.png?dl=0

* collapse not active chapters and/or implement a hover accordion. 
* background image for the summary (same as nooku.org hero)
* font change to "Roboto, Helvetica, Arial, sans-serif;" and smaller by roughly 15% (similar to djangodocs)
* widen content area to 90% of the available. 

If we decide to go ahead I'll create a new "issue"

**Comment by johanjanssens** [comment]
@magneticmg Good work. Lets go ahead and make these changes to the template. Looking great. If needed include @robinpoort

**Comment by magneticmg** [comment]
Great. I'll go ahead do the changes and get @robinpoort to checkout what I've done.

**Comment by magneticmg** [comment]
@robinpoort 

I'd love it if you would pull down this feature branch, build and let me know what you think. Feel free to make any changes you like as well
![new-guides-styling](https://cloud.githubusercontent.com/assets/364980/6922898/62a32476-d79c-11e4-9a86-6c4cb159b8a3.png).
* I've added a gitbook plugin to help handle some of the 'expanded' styling (node_modules/gitbook-plugin-summary/book/plugin.js)
*  All CSS is in the /theme/assets/custom.css file. 

Also, @johanjanssens, let me know what you think about getting rid of the numbers in front of the "Chapter" headings.

**Comment by robinpoort** [comment]
@magneticmg @johanjanssens I've styled the sidebar among some other small things.

![gitbook](https://cloud.githubusercontent.com/assets/4848082/6960758/982884e4-d925-11e4-9a13-64070600c132.png)

Some things I did:
* Larger font in the sidebar for readability
* Proper Timble color for links in sidebar and content
* removed the blue image background because it didn't look very good on larger screens.
* Sidebar is just the default color because the contrast between current section and other sections was a bit to large.
* Also you can choose themes as a reader (by clicking the "A" on top of content) and the blue looked ridiculous on sepia and night themes :)
* Loading the JS logic in `layout.html`. Could you remove it from the plugins Cameron?
* @tomjanssens and I decided to remove the "done" checkmarks since this can't be found on any other documentation tool on the internet and it can be confusing. If you click something to check if the info your looking for is there but it's not and you click on the next chapter it does register that you read the chapter.

@magneticmg I'd remove the numbers in front of the chapters because I don't really think it has any use.

**Comment by magneticmg** [comment]
Hi Robin, Thanks for that. 

For me, these changes are way too much like the original.

* The "A": I didn't know that. My opinion is that we can get rid of the theme selection in that drop down (both don't look very good). 
* The links in the sidebar were large enough (almost too much so) before, IMO.
* The side bar default background color is just too white. I think we need some contrast between the current section and the other sections. If the white-blue contrast is too much, maybe we can find a middle ground. Here was my inspiration for doing something like that: http://bootstrap-datepicker.readthedocs.org/en/latest/methods.html
* Awesome about the check marks. 
* Numbers: I totally agree. 
* I would still like to show the entire list of chapters under a main chapter (Unless we are going to add some accordion hovering). Otherwise, I have to click each link in a sub-chapter to know if there is anything in it. 
* I had made the inner page with a maximum of 90% of the available space instead of 800px, which leaves way too much white space on large screens; that change is gone. 
* The font I had chosen was: "Roboto, Helvetica, Arial, sans-serif;" which is in line with Nooku.org and looks a little better IMO.

**Comment by robinpoort** [comment]
Hi Cameron,

The fact that it's more like the original is a good thing to me. People who are used to gitbook will like the fact that it works and looks like they expect.

* The "A" can stay because of my first point. If they want to use it why not give them an option to? It's not the most beautiful themes ever but they are very decent. Especially the night theme could come in handy when it's dark around you.
* The links are a tiny bit smaller again. But shouldn't be any smaller than this. Readability is the key here.
* I am familiar with the readthedocs style and dislike it. We also need to add a lot of CSS to make links, hovers, focus etc. work. At the moment it's clear with just little CSS and looks better in my opinion.
* I removed the numbers in the `summary.html` file
* Now showing all children of parent items. Accordion on hover is not going to happen because that won't work on touch devices and keyboard navigation. Opening items with a small arrow or '+' is also not going to happen because that's just as fast as clicking the item itself like in the previous commit.
* The inner width is 800px on purpose. The white-space is needed so we don't get lines that are super long on larger screens. The preffered amount of words on one line is about 12 to 15. More words will make it really hard to jump to the begin of the next sentence.
* I accidentally removed that one and didn't put it back. Thanks for noticing! It's back now.

**Comment by robinpoort** [comment]
![guides](https://cloud.githubusercontent.com/assets/4848082/6963942/d1c08980-d944-11e4-83eb-9d4ca70cf851.png)

**Comment by tomjanssens** [comment]
This looks great! Agreed with @robinpoort on the reasoning behind his made changes.

All systems `green`, you can deploy.

**Comment by magneticmg** [comment]
Thanks @robinpoort,( and @tomjanssens )

Thanks for taking some of the suggestions. Its a good first iteration. Getting rid of the checkmarks, numbers, collapsing the sections and font change are big wins I think.

I'd still like to see more contrast between the active and not active section in the summary, and am still set against the centered 800px on large screens (maybe if there was less space from the left edge of the content to the summary it would bother me less).

Anyway, good work @robinpoort. Will deploy this later today then.

**Comment by tomjanssens** [comment]
@magneticmg for the line-length we are following general accessibility guidelines. From [webaim.org](http://webaim.org/techniques/textlayout/#column_width): `in general, fewer than around 50 or more than around 120 characters per line will likely introduce difficulty.`

Center aligning the whole gitbook area is not easily possible since we need to override a lot of Gitbook CSS. Which would make it also vulnerable for issues when upgrading Gitbook. So let's not worry about the white space between the sidebar and the content on big screens.

Changes have been deployed, closing the ticket.

**Comment by johanjanssens** [comment]
@robinpoort @magneticmg @tomjanssens Good work guys. This is much better! 

For what it is worth I did like Cameron his orginial idea to bring a bit more blue into the sidebar to make the sidebar and navigation stand out from the actual text. I'll let you guys battle that one out further on the workshop. I'll be cheering! :)
